adding

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -14,7 +14,7 @@ on:
         options:
           - apply
           - destroy
- 
+
 jobs:
   terraform:
     runs-on: ubuntu-latest
@@ -29,7 +29,7 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+          aws-region: eu-north-1
 
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
@@ -49,34 +49,37 @@ jobs:
           fi
 
   ecs-deploy:
-    runs-on: ubuntu-latest 
+    runs-on: ubuntu-latest
     needs: terraform
     if: ${{ github.event.inputs.action == 'apply' }}
+    env:
+      AWS_REGION: eu-north-1
+      AWS_DEFAULT_REGION: eu-north-1
     steps:
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_REGION }}
+          aws-region: eu-north-1
 
       - name: Get latest ECS Task Definition ARN
         id: get_task_def
         run: |
-          TASK_ARN=$(aws ecs list-task-definitions \
-          --family-prefix strapi-task-reshma \
-          --sort DESC \
-          --max-items 1 \
-          --query 'taskDefinitionArns[0]' \
-          --output text)
+          set -e
 
-          if [ -z "$TASK_ARN" ] || [ "$TASK_ARN" == "None" ]; then
-          echo "ERROR: No ECS task definition found for family strapi-task-reshma"
-          exit 1
+          TASK_ARN=$(aws ecs list-task-definitions \
+            --family-prefix strapi-task-reshma \
+            --sort DESC \
+            --query 'taskDefinitionArns[0]' \
+            --output text)
+
+          if [ -z "$TASK_ARN" ] || [ "$TASK_ARN" = "None" ]; then
+            echo "❌ ERROR: No ECS task definition found for family strapi-task-reshma"
+            exit 1
           fi
 
-          echo "taskDefinitionArn=$TASK_ARN" >> "$GITHUB_OUTPUT"
-
+          printf "taskDefinitionArn=%s\n" "$TASK_ARN" >> "$GITHUB_OUTPUT"
 
       - name: Trigger CodeDeploy Deployment
         run: |
@@ -109,6 +112,7 @@ jobs:
             --deployment-config-name CodeDeployDefault.ECSCanary10Percent5Minutes \
             --revision "$REVISION_JSON" \
             --description "GitHub Actions deployment - taskdef ${TASK_DEF_ARN##*:}"
+
 
  
 # name: CD - Terraform Deploy
